### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by Sephirox** [drspod/drScoreBadger#1]
Awesome, my questions is this set so it only works when on a BG/Arena? Hopefully its not sucking performance while out of a PvP Instance .>.<. trying to find healers.

EDIT: Would be nice if the Tag was on top of their heads instead of below, maybe a few pixels on top so it doesn't overlap with the nameplates? Aside from that really nice addon. The Healer and Bubble tag is a bit too much maybe give us the option to use the bubble/+ or just the + Tag. If the bubble/+ is on top would be nice to flip it so the narrow part faces down and the wider part faces up for more visibility.

**Comment by Sephirox** [comment]
Also a way to change the tag color, it fades on Walatiki with the green pasture.

**Comment by drspod** [comment]
I have added options for badge height, size and opacity, and some different badge sprites to choose from.
